name: Configlet CI

on: [push, pull_request, workflow_dispatch]

jobs:
  configlet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

    - name: Fetch configlet
      uses: exercism/github-actions/configlet-ci@main
        
    - name: Configlet Linter
      run: configlet lint
